# Generated by Django 3.0.3 on 2020-04-25 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200415_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fallow',
            new_name='Follow',
        ),
    ]
