# Generated by Django 3.0.3 on 2020-05-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200503_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
